---

- name: Copy install script
  template:
    src: install.sh.j2
    dest: /uim/install.sh
    mode: 755

- name: Create a guard for script
  stat:
    path: /sysadmin/uim_install_log.txt
  register: uim_install

- name: Execute script
  shell: /uim/install.sh
  when: uim_install.stat
